//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Точка_прокатаЦПКиО.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        public int ID { get; set; }
        public string Код_заказа { get; set; }
        public Nullable<System.DateTime> Дата_создания { get; set; }
        public Nullable<System.TimeSpan> Время_заказа { get; set; }
        public Nullable<int> IDКлиента { get; set; }
        public Nullable<int> IDУслуги { get; set; }
        public Nullable<int> IDСтатус { get; set; }
        public Nullable<System.DateTime> Дата_закрытия { get; set; }
        public string Время_проката { get; set; }
        public Nullable<int> IDСотрудника { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Статусы Статусы { get; set; }
        public virtual Услуги Услуги { get; set; }
    }
}
